-- Add missing columns to invoice_templates table
ALTER TABLE invoice_templates ADD COLUMN IF NOT EXISTS send_copy boolean DEFAULT false;
ALTER TABLE invoice_templates ADD COLUMN IF NOT EXISTS timezone text;
ALTER TABLE invoice_templates ADD COLUMN IF NOT EXISTS locale text DEFAULT 'en-US';

-- Insert default invoice template for demo team if not exists
INSERT INTO invoice_templates (
  team_id,
  customer_label,
  title,
  from_label,
  invoice_no_label,
  issue_date_label,
  due_date_label,
  description_label,
  price_label,
  quantity_label,
  total_label,
  total_summary_label,
  vat_label,
  tax_label,
  discount_label,
  payment_label,
  note_label,
  subtotal_label,
  currency,
  date_format,
  include_vat,
  include_tax,
  include_discount,
  include_decimals,
  include_pdf,
  send_copy,
  include_units,
  include_qr,
  tax_rate,
  vat_rate,
  size,
  delivery_type,
  locale,
  timezone
) VALUES (
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
  'Bill To',
  'Invoice',
  'From',
  'Invoice #',
  'Issue Date',
  'Due Date',
  'Description',
  'Rate',
  'Qty',
  'Amount',
  'Total',
  'VAT',
  'Sales Tax',
  'Discount',
  'Payment Information',
  'Notes',
  'Subtotal',
  'USD',
  'MM/dd/yyyy',
  false,
  false,
  false,
  true,
  true,
  false,
  true,
  false,
  0,
  0,
  'a4',
  'create',
  'en-US',
  'America/Los_Angeles'
)
ON CONFLICT (team_id) DO NOTHING;
